"""Final functional alignment

Revision ID: 7c286fd41f57
Revises: 537284997112
Create Date: 2026-07-23 15:38:51.431816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c286fd41f57'
down_revision: Union[str, Sequence[str], None] = '537284997112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_listings_is_starred'), 'job_listings', ['is_starred'], unique=False)
    op.create_index('ix_joblistings_user_status', 'job_listings', ['user_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_joblistings_user_status', table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_is_starred'), table_name='job_listings')
    # ### end Alembic commands ###
